// <auto-generated />
namespace WissAppEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class WissApp_v20 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WissApp_v20));
        
        string IMigrationMetadata.Id
        {
            get { return "202002241715488_WissApp_v2.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
